package ac.technion.iem.ontobuilder.gui.ontobuilder.elements;

import java.awt.event.ActionEvent;

import javax.swing.JDialog;

import ac.technion.iem.ontobuilder.gui.elements.AbsoluteConstraints;
import ac.technion.iem.ontobuilder.gui.elements.AbsoluteLayout;

/**
 * <p>Title: ThresholdDialog</p>
 * Extends a {@link JDialog}
 * @author haggai
 */
public class ThresholdDialog extends JDialog
{

    private static final long serialVersionUID = 1L;

    private double thresholdValue;

    /**
     * Creates new form JDialog
     * 
     * @param parent the parent {@link JDialog}
     * @param thresholdValue the threshold value
     */
    public ThresholdDialog(JDialog parent, double thresholdValue)
    {
        super(parent, true);
        this.thresholdValue = thresholdValue;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    private void initComponents()
    {
        jLabel1 = new javax.swing.JLabel();
        threshold = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();

        getContentPane().setLayout(new AbsoluteLayout());

        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                closeDialog(evt);
            }
        });
        setTitle("Average Aggregator Threshold");
        jLabel1.setText("Enter Threshold:");
        getContentPane().add(jLabel1, new AbsoluteConstraints(10, 50, 130, -1));
        threshold.setText("" + thresholdValue);
        getContentPane().add(threshold, new AbsoluteConstraints(130, 50, 90, -1));

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                okButtonActionPerformed(evt);
            }
        });

        getContentPane().add(okButton, new AbsoluteConstraints(110, 100, -1, -1));

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setSize(new java.awt.Dimension(254, 173));
        setLocation((screenSize.width - 254) / 2, (screenSize.height - 173) / 2);
    }

    /**
     * Executes an "OK" button action
     * 
     * @param evt the event performed
     */
    private void okButtonActionPerformed(ActionEvent evt)
    {
        try
        {
            thresholdValue = Double.parseDouble(threshold.getText());
        }
        catch (NumberFormatException e)
        {
            thresholdValue = 0;
        }
        dispose();
    }

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt)
    {
        setVisible(false);
        dispose();
    }

    /**
     * Get the threshold
     * 
     * @return the threshold value
     */
    public double getThreshold()
    {
        return thresholdValue;
    }

    // Variables declaration - do not modify
    private javax.swing.JButton okButton;
    private javax.swing.JTextField threshold;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration

}
